import type { Ebook } from "@/lib/types";

export const ebookLibrary: Ebook[] = [
  {
    id: "the-way",
    title: "The Way",
    author: "St. Josemaria Escriva",
    sourceUrl: "https://escriva.org/en/camino/",
    languages: {
      en: {
        title: "The Way",
        description:
          "A classic collection of 999 short points for prayer, holiness in ordinary life, and apostolic courage.",
        attribution: "Read the official free text on escriva.org.",
      },
      zhHant: {
        title: "道路",
        description:
          "聖施禮華的經典靈修著作，包含 999 則短篇默想，幫助人在日常生活中追求成聖與使徒精神。",
        attribution: "請在 escriva.org 閱讀官方免費文本。",
      },
    },
    chapters: [
      { id: "character", title: "Character", startPoint: 1, endPoint: 55, sourceUrl: "https://escriva.org/en/camino/character/" },
      { id: "guidance", title: "Guidance", startPoint: 56, endPoint: 80, sourceUrl: "https://escriva.org/en/camino/guidance/" },
      { id: "prayer", title: "Prayer", startPoint: 81, endPoint: 117, sourceUrl: "https://escriva.org/en/camino/prayer/" },
      { id: "holy-purity", title: "Holy purity", startPoint: 118, endPoint: 145, sourceUrl: "https://escriva.org/en/camino/holy-purity/" },
      { id: "heart", title: "Heart", startPoint: 146, endPoint: 171, sourceUrl: "https://escriva.org/en/camino/heart/" },
      { id: "mortification", title: "Mortification", startPoint: 172, endPoint: 207, sourceUrl: "https://escriva.org/en/camino/mortification/" },
      { id: "penance", title: "Penance", startPoint: 208, endPoint: 234, sourceUrl: "https://escriva.org/en/camino/penance/" },
      { id: "examination-of-conscience", title: "Examination of conscience", startPoint: 235, endPoint: 246, sourceUrl: "https://escriva.org/en/camino/examination-of-conscience/" },
      { id: "resolutions", title: "Resolutions", startPoint: 247, endPoint: 257, sourceUrl: "https://escriva.org/en/camino/resolutions/" },
      { id: "scruples", title: "Scruples", startPoint: 258, endPoint: 264, sourceUrl: "https://escriva.org/en/camino/scruples/" },
      { id: "presence-of-god", title: "Presence of God", startPoint: 265, endPoint: 278, sourceUrl: "https://escriva.org/en/camino/presence-of-god/" },
      { id: "supernatural-life", title: "Supernatural life", startPoint: 279, endPoint: 300, sourceUrl: "https://escriva.org/en/camino/supernatural-life/" },
      { id: "more-about-interior-life", title: "More about interior life", startPoint: 301, endPoint: 324, sourceUrl: "https://escriva.org/en/camino/more-about-interior-life/" },
      { id: "lukewarmness", title: "Lukewarmness", startPoint: 325, endPoint: 331, sourceUrl: "https://escriva.org/en/camino/lukewarmness/" },
      { id: "study", title: "Study", startPoint: 332, endPoint: 359, sourceUrl: "https://escriva.org/en/camino/study/" },
      { id: "formation", title: "Formation", startPoint: 360, endPoint: 386, sourceUrl: "https://escriva.org/en/camino/formation/" },
      { id: "your-holiness", title: "Your holiness", startPoint: 387, endPoint: 416, sourceUrl: "https://escriva.org/en/camino/your-holiness/" },
      { id: "love-of-god", title: "Love of God", startPoint: 417, endPoint: 439, sourceUrl: "https://escriva.org/en/camino/love-of-god/" },
      { id: "charity", title: "Charity", startPoint: 440, endPoint: 469, sourceUrl: "https://escriva.org/en/camino/charity/" },
      { id: "the-means", title: "The means", startPoint: 470, endPoint: 491, sourceUrl: "https://escriva.org/en/camino/the-means/" },
      { id: "our-lady", title: "Our Lady", startPoint: 492, endPoint: 516, sourceUrl: "https://escriva.org/en/camino/our-lady/" },
      { id: "the-church", title: "The Church", startPoint: 517, endPoint: 527, sourceUrl: "https://escriva.org/en/camino/the-church/" },
      { id: "holy-mass", title: "Holy Mass", startPoint: 528, endPoint: 543, sourceUrl: "https://escriva.org/en/camino/holy-mass/" },
      { id: "communion-of-saints", title: "Communion of saints", startPoint: 544, endPoint: 550, sourceUrl: "https://escriva.org/en/camino/communion-of-saints/" },
      { id: "devotions", title: "Devotions", startPoint: 551, endPoint: 574, sourceUrl: "https://escriva.org/en/camino/devotions/" },
      { id: "faith", title: "Faith", startPoint: 575, endPoint: 588, sourceUrl: "https://escriva.org/en/camino/faith/" },
      { id: "humility", title: "Humility", startPoint: 589, endPoint: 613, sourceUrl: "https://escriva.org/en/camino/humility/" },
      { id: "obedience", title: "Obedience", startPoint: 614, endPoint: 629, sourceUrl: "https://escriva.org/en/camino/obedience/" },
      { id: "poverty", title: "Poverty", startPoint: 630, endPoint: 638, sourceUrl: "https://escriva.org/en/camino/poverty/" },
      { id: "discretion", title: "Discretion", startPoint: 639, endPoint: 656, sourceUrl: "https://escriva.org/en/camino/discretion/" },
      { id: "cheerfulness", title: "Cheerfulness", startPoint: 657, endPoint: 666, sourceUrl: "https://escriva.org/en/camino/cheerfulness/" },
      { id: "other-virtues", title: "Other virtues", startPoint: 667, endPoint: 684, sourceUrl: "https://escriva.org/en/camino/other-virtues/" },
      { id: "troubles", title: "Troubles", startPoint: 685, endPoint: 706, sourceUrl: "https://escriva.org/en/camino/troubles/" },
      { id: "interior-struggle", title: "Interior struggle", startPoint: 707, endPoint: 733, sourceUrl: "https://escriva.org/en/camino/interior-struggle/" },
      { id: "last-things", title: "Last things", startPoint: 734, endPoint: 753, sourceUrl: "https://escriva.org/en/camino/last-things/" },
      { id: "the-will-of-god", title: "The will of God", startPoint: 754, endPoint: 778, sourceUrl: "https://escriva.org/en/camino/the-will-of-god/" },
      { id: "the-glory-of-god", title: "The glory of God", startPoint: 779, endPoint: 789, sourceUrl: "https://escriva.org/en/camino/the-glory-of-god/" },
      { id: "winning-new-apostles", title: "Winning new apostles", startPoint: 790, endPoint: 812, sourceUrl: "https://escriva.org/en/camino/winning-new-apostles/" },
      { id: "little-things", title: "Little things", startPoint: 813, endPoint: 830, sourceUrl: "https://escriva.org/en/camino/little-things/" },
      { id: "tactics", title: "Tactics", startPoint: 831, endPoint: 851, sourceUrl: "https://escriva.org/en/camino/tactics/" },
      { id: "spiritual-childhood", title: "Spiritual childhood", startPoint: 852, endPoint: 874, sourceUrl: "https://escriva.org/en/camino/spiritual-childhood/" },
      { id: "life-of-childhood", title: "Life of childhood", startPoint: 875, endPoint: 901, sourceUrl: "https://escriva.org/en/camino/life-of-childhood/" },
      { id: "calling", title: "Calling", startPoint: 902, endPoint: 928, sourceUrl: "https://escriva.org/en/camino/calling/" },
      { id: "the-apostle", title: "The apostle", startPoint: 929, endPoint: 959, sourceUrl: "https://escriva.org/en/camino/the-apostle/" },
      { id: "the-apostolate", title: "The apostolate", startPoint: 960, endPoint: 982, sourceUrl: "https://escriva.org/en/camino/the-apostolate/" },
      { id: "perseverance", title: "Perseverance", startPoint: 983, endPoint: 999, sourceUrl: "https://escriva.org/en/camino/perseverance/" },
    ],
  },
];
